#ifndef CONFIG_H
#define CONFIG_H

#include "typedefine.h"

#define CONFIG_FILE "./config/config.txt"
#define CONFIG_LINE_BUFFER_SIZE 100
#define MAX_CONFIG_VARIABLE_LEN 100

extern config_object_t config;

int config_init();

/* Return codes of config */ 
typedef enum config_err {
    CONFIG_ACCEPT = 0,
    CONFIG_INVALID_RSU_ID = -1,
    CONFIG_INVALID_RSU_LAT = -2,
    CONFIG_INVALID_RSU_LON = -3,
    CONFIG_INVALID_SIGNAL_CONTROLLER_MANUFACTURER = -4,
    CONFIG_INVALID_SIGNAL_STATUS_REPORT_ACTIVE = -5,
    CONFIG_INVALID_SIGNAL_ADJUST_UPPER_BOUND_ACTVE = -6,
    CONFIG_INVALID_SIGNAL_ADJUST_LOWER_BOUND_ACTVE = -7,
    CONFIG_INVALID_SIGNAL_ADJUST_UPPER_BOUND_PERCENTAGE = -8,
    CONFIG_INVALID_SIGNAL_ADJUST_LOWER_BOUND_PERCENTAGE = -9,
    CONFIG_INVALID_LOG_MIDDLEWARE_TIMER_EVENT = -10,
    CONFIG_INVALID_LOG_APPLICATION_REGISTER_EVENT = -11,
    CONFIG_INVALID_LOG_COMMAND_BUFFER = -12,
    CONFIG_INVALID_LOG_SIGNAL_PACKET_RX = -13,
    CONFIG_INVALID_LOG_SIGNAL_PACKET_TX = -14,
    CONFIG_INVALID_LOG_SIGNAL_PACKET_INFO = -15,
    CONFIG_INVALID_LOG_CLOUD_PACKET_RX = -16,
    CONFIG_INVALID_LOG_CLOUD_PACKET_TX = -17,
    CONFIG_INVALID_LOG_OBU_PACKET_RX = -18,
    CONFIG_INVALID_LOG_OBU_PACKET_TX = -19,
    CONFIG_INVALID_LOG_OBU_LIST = -20,
    CONFIG_INVALID_TRAFFIC_COMPENSATION_METHOD = -21,
    CONFIG_INVALID_PHASE_WEIGHT = -22
} config_err_t;

#endif