#ifndef EXTERNAL_APP_PROXY_TYPEDEFINE_H
#define EXTERNAL_APP_PROXY_TYPEDEFINE_H

/* DANGER: this file: external_app_proxy_typedefine.h
 * will exist both is server-side and client-side
 * the two should be "THE SAME" !! */

/* EAL stands for External-Application-Library*/
enum ea_err_definition_enum {
    /* no err */
    EAL_ERR_OK = 0,
    
    /* OS-syscall or OS-lib-call err*/
    EAL_ERR_SOCKET_SYSCALL,
    EAL_ERR_SOCKET_DISCONNECT,
    EAL_ERR_EPOLL_SYSCALL,
    EAL_ERR_MEMORY_LIB,
    EAL_ERR_J2735_MSG_ENCODE,
    EAL_ERR_J2735_MSG_DECODE,

    /* our library detected err */
    EAL_ERR_CONNECT_TO_PROXY_TIMEOUT,
    EAL_ERR_CONNECT_TO_PROXY_FAIL,
    EAL_ERR_PACKET_TYPE_NOT_MATCH,
    EAL_ERR_PACKET_BAD_CONTENT,
    EAL_ERR_HEARTBEAT_SETTING,
    EAL_ERR_APP_NOT_REGISTER_YET,
    EAL_ERR_CALLBACK_NOT_DEFINED_IN_SYSTEM,
    EAL_ERR_CALLBACK_NOT_REGISTER_TO_MW,
    EAL_ERR_CALLBACK_NOT_SUPPORT_IN_CURRENT_VERSION,
    EAL_ERR_CALLBACK_NOT_DEFINED_BY_CUR_APP,
    EAL_ERR_BAD_PARAMETER,
    EAL_ERR_BAD_PACKET_TYPE_BEFORE_REGISTER,
    EAL_ERR_BAD_PACKET_TYPE_TO_MIDDLEWARE,
    EAL_ERR_BAD_API_ID_BEFORE_REGISTER,
    EAL_ERR_IN_MIDDLEWARE_REGISTER_REJECT,
    EAL_ERR_LIB_SEND_WRONG_PACKET_TYPE,
    EAL_ERR_BAD_PACKET_TYPE_RECEIVE_FROM_MIDDLEWARE,

    /* error detected when calling the actual api in middleware */
    EAL_ERR_IN_MIDDLEWARE_ERR_COM_IO,
    EAL_ERR_IN_MIDDLEWARE_API_INTERNAL,
    EAL_ERR_IN_MIDDLEWARE_HEARTBEAT_UPDATE_FOR_APP,
    
    /* this tag should always be at the last */
    NUM_OF_EA_ERR_DEF,
};

#endif  /* EXTERNAL_APP_PROXY_TYPEDEFINE_H */