#ifndef EXTERNAL_APP_PROXY_TYPEDEFINE_H
#define EXTERNAL_APP_PROXY_TYPEDEFINE_H

/* this file should be the same as in server side (i.e., middleware) */

enum ea_err_definition_enum {
    EA_ERR_OK = 0,
    EA_ERR_SOCKET_CREATE,
    EA_ERR_SOCKET_CONNECT,
    EA_ERR_SOCKET_READ,
    EA_ERR_SOCKET_WRITE,
    EA_ERR_SOCKET_CLOSE,
    EA_ERR_API_UNDEFINDED,
    EA_ERR_BAD_PARAMETER,
    EA_ERR_J2735_MSG_ENCODE,
    EA_ERR_MEMORY_LIB,
    EA_ERR_COM_IO,
    EA_ERR_ACTUAL_FUNCTION_ERR,

    EA_ERR_PACKET_TYPE_NOT_MATCH,
    EA_ERR_UNKNOWN_CALLBACK_BIT_FROM_MW,
    EA_ERR_CALLBACK_NOT_REGISTER_TO_MW,
    EA_ERR_CALLBACK_NOT_DEFINED_BY_APP,
    EA_ERR_CALLBACK_NOT_DEFINED_IN_SYSTEM,
    EA_ERR_BAD_CALLBACKMASK_FROM_MW,
    EA_ERR_BAD_API_ID_BEFORE_REGISTER,
    EA_ERR_BAD_CHANNEL_FROM_APP,
    EA_ERR_BAD_PACKET_TYPE_BEFORE_REGISTER,
    EA_ERR_BAD_PACKET_TYPE_REGISTER_ORDER,
    EA_ERR_BAD_PACKET_TYPE_FROM_INTERACT_CHANNEL,
    
    /* this tag should always be at the last */
    NUM_OF_EA_ERR_DEF,
};

#endif  /* EXTERNAL_APP_PROXY_TYPEDEFINE_H */